# Generated by Django 4.2 on 2023-08-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
    ]
