# Generated by Django 4.2 on 2023-08-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_comment_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(default=None),
        ),
    ]
